#!/usr/bin/env python3
"""Generate a deployment config for acdc-validator: scans the server for CPU/RAM,
asks a couple of sizing questions, and writes a systemd unit + .env file under
./deploy/generated/. Nothing is installed or started unless you pass --apply.

Usage:
    env/bin/python deploy.py                # scan + ask + generate (safe, no system changes)
    env/bin/python deploy.py --apply        # also offer to install/enable/start (sudo)
    env/bin/python deploy.py --yes ...      # skip confirmation prompts

Standard library only — no extra dependencies.
"""
import argparse
import getpass
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
GENERATED_DIR = REPO_ROOT / "deploy" / "generated"


# ── server scanning ──────────────────────────────────────────────────────────

def detect_cpus() -> int:
    return os.cpu_count() or 1


def detect_ram_mb() -> int:
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    return int(line.split()[1]) // 1024
    except FileNotFoundError:
        pass
    return 0


def detect_python_bin() -> str:
    venv_python = REPO_ROOT / "env" / "bin" / "python"
    return str(venv_python) if venv_python.exists() else sys.executable


def detect_gunicorn_bin() -> str:
    venv_gunicorn = REPO_ROOT / "env" / "bin" / "gunicorn"
    return str(venv_gunicorn) if venv_gunicorn.exists() else "gunicorn"


# ── recommendation logic ─────────────────────────────────────────────────────

def recommend(cpus: int, ram_mb: int, expected_users: int, other_apps: int) -> dict:
    """This app is SQLite-backed with no background workers, so we only need
    to size a single gunicorn process. One worker + gthread is the right shape
    for SQLite (one writer at a time); thread count tracks concurrent users."""
    share = other_apps + 1
    budget_cpus = max(1, cpus // share)
    budget_ram_mb = max(256, ram_mb // share)

    # Threads: enough to cover expected concurrent users without over-provisioning.
    # Cap at 2× budget CPUs to avoid excessive context-switching.
    gunicorn_threads = max(2, min(expected_users, budget_cpus * 2, 16))

    return {
        "budget_cpus": budget_cpus,
        "budget_ram_mb": budget_ram_mb,
        "gunicorn_workers": 1,
        "gunicorn_threads": gunicorn_threads,
    }


# ── file templates ───────────────────────────────────────────────────────────

SERVICE_TEMPLATE = """\
[Unit]
Description=acdc-validator — ALTO annotation web app
After=network.target

[Service]
User={user}
Group=www-data
WorkingDirectory={repo_root}
Environment="PATH={venv_bin}"
EnvironmentFile=-{repo_root}/.env
ExecStart={gunicorn_bin} --workers {gunicorn_workers} --worker-class gthread \\
    --threads {gunicorn_threads} --timeout 120 \\
    --bind unix:{repo_root}/{app_name}.sock -m 007 \\
    --log-syslog --log-level=info --capture-output \\
    run:app
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

NGINX_TEMPLATE = """\
# Suggested nginx server block — place in /etc/nginx/sites-available/{app_name}
# and symlink to sites-enabled/, then: sudo nginx -t && sudo systemctl reload nginx

server {{
    listen 80;
    server_name {server_name};

    # Redirect HTTP → HTTPS (uncomment after certbot setup)
    # return 301 https://$host$request_uri;

    location / {{
        include proxy_params;
        proxy_pass http://unix:{repo_root}/{app_name}.sock;
        proxy_read_timeout 120s;
    }}

    # Serve static files directly for performance
    location /static/ {{
        alias {repo_root}/app/static/;
        expires 1d;
        add_header Cache-Control "public";
    }}
}}
"""

ENV_TEMPLATE = """\
# Generated by deploy.py — review before use, then copy to .env
# (your existing .env is never overwritten automatically)
FLASK_APP=run.py
SECRET_KEY={secret_key}
DATABASE_URL=sqlite:///{repo_root}/annotations.db
DATA_PATH={repo_root}/book-samples
# Optional: set to a custom path if your book-samples folder is elsewhere
# DATA_PATH=/mnt/data/book-samples
"""


# ── file generation ──────────────────────────────────────────────────────────

def generate_files(app_name: str, server_name: str, rec: dict) -> list[Path]:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    user = getpass.getuser()
    venv_bin = str(REPO_ROOT / "env" / "bin")
    gunicorn_bin = detect_gunicorn_bin()
    secret_key = _random_secret()

    written = []

    service_path = GENERATED_DIR / f"{app_name}.service"
    service_path.write_text(SERVICE_TEMPLATE.format(
        app_name=app_name, user=user, repo_root=REPO_ROOT,
        venv_bin=venv_bin, gunicorn_bin=gunicorn_bin,
        gunicorn_workers=rec["gunicorn_workers"],
        gunicorn_threads=rec["gunicorn_threads"],
    ))
    written.append(service_path)

    nginx_path = GENERATED_DIR / f"{app_name}.nginx"
    nginx_path.write_text(NGINX_TEMPLATE.format(
        app_name=app_name, repo_root=REPO_ROOT, server_name=server_name,
    ))
    written.append(nginx_path)

    env_path = GENERATED_DIR / ".env.recommended"
    env_path.write_text(ENV_TEMPLATE.format(
        repo_root=REPO_ROOT, secret_key=secret_key,
    ))
    written.append(env_path)

    return written


def _random_secret(length: int = 48) -> str:
    import secrets, string
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


# ── interactive helpers ───────────────────────────────────────────────────────

def ask_int(prompt: str, default: int) -> int:
    raw = input(f"{prompt} [{default}]: ").strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        print(f"  Not a number, using default {default}.")
        return default


def ask_str(prompt: str, default: str) -> str:
    raw = input(f"{prompt} [{default}]: ").strip()
    return raw or default


def confirm(prompt: str, assume_yes: bool) -> bool:
    if assume_yes:
        return True
    return input(f"{prompt} [y/N]: ").strip().lower() in ("y", "yes")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="After generating files, offer to install/enable/start them via sudo.")
    parser.add_argument("--yes", action="store_true",
                        help="Skip confirmation prompts (still requires --apply to touch the system).")
    parser.add_argument("--app-name", default="acdc-validator",
                        help="Base name for the systemd unit and socket (default: acdc-validator).")
    parser.add_argument("--users", type=int, default=None,
                        help="Expected simultaneous users (skips the interactive prompt).")
    parser.add_argument("--other-apps", type=int, default=None,
                        help="Other apps/services already running on this box (skips the prompt).")
    parser.add_argument("--server-name", default=None,
                        help="Hostname for the nginx block (e.g. validator.example.com).")
    args = parser.parse_args()

    print("== Scanning this server ==")
    cpus = detect_cpus()
    ram_mb = detect_ram_mb()
    print(f"  CPUs : {cpus}")
    print(f"  RAM  : {ram_mb} MB ({ram_mb / 1024:.1f} GB)")
    print(f"  Python: {detect_python_bin()}")

    print()
    print("== Sizing questions ==")
    expected_users = args.users if args.users is not None else \
        ask_int("Expected simultaneous users", 5)
    other_apps = args.other_apps if args.other_apps is not None else \
        ask_int("Other apps/services already running on this box", 0)
    server_name = args.server_name or \
        ask_str("Hostname for nginx server_name", "validator.example.com")

    rec = recommend(cpus, ram_mb, expected_users, other_apps)

    print()
    print("== Recommendations ==")
    print(f"  Resource budget : {rec['budget_cpus']} CPUs, {rec['budget_ram_mb']} MB RAM")
    print(f"  gunicorn        : --workers {rec['gunicorn_workers']} --worker-class gthread --threads {rec['gunicorn_threads']}")

    print()
    print("== Generating files ==")
    written = generate_files(args.app_name, server_name, rec)
    for p in written:
        print(f"  wrote  {p.relative_to(REPO_ROOT)}")

    rel = GENERATED_DIR.relative_to(REPO_ROOT)
    print()
    print("Next steps (review the generated files first):")
    print(f"  1. cp {rel}/.env.recommended .env")
    print(f"     # edit .env — set DATA_PATH if book-samples is not in {REPO_ROOT}")
    print(f"  2. env/bin/flask init          # populate DB and convert PNGs → JPGs")
    print(f"  3. env/bin/flask user add <name>")
    print(f"  4. sudo cp {rel}/{args.app_name}.service /etc/systemd/system/")
    print(f"     sudo systemctl daemon-reload")
    print(f"     sudo systemctl enable --now {args.app_name}")
    print(f"  5. sudo cp {rel}/{args.app_name}.nginx /etc/nginx/sites-available/{args.app_name}")
    print(f"     sudo ln -s /etc/nginx/sites-available/{args.app_name} /etc/nginx/sites-enabled/")
    print(f"     sudo nginx -t && sudo systemctl reload nginx")

    if not args.apply:
        print()
        print("(Run with --apply to have this script offer to run the install steps for you.)")
        return

    print()
    service_path = GENERATED_DIR / f"{args.app_name}.service"
    if confirm(f"Install {service_path.name} to /etc/systemd/system and start it now?", args.yes):
        subprocess.run(f"sudo cp {service_path} /etc/systemd/system/", shell=True, check=True)
        subprocess.run("sudo systemctl daemon-reload", shell=True, check=True)
        subprocess.run(f"sudo systemctl enable --now {args.app_name}", shell=True, check=True)
        print("Installed and started.")
    else:
        print("Skipped. Files are in deploy/generated/ for manual install.")


if __name__ == "__main__":
    main()
